name: Auto Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/dcx7c5/dcrypto.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master  # or your default branch
          git merge upstream/master --allow-unrelated-histories --no-edit || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master  # or your default branch
